AddArt("yearosnake c", "", "yearosnake_c", "jpg");
AddArt("wolves-n-pig", "", "wolves-n-pig", "jpg");
AddArt("wingedfox digital", "", "wingedfox_digital", "jpg");
AddArt("snowleapord", "", "snowleapord", "jpg");
AddArt("whiterabbit fel", "", "whiterabbit_fel", "jpg");
AddArt("soulfox gift", "", "soulfox_gift", "jpg");
AddArt("sk p spot", "", "sk_p_spot", "jpg");
AddArt("sk blkpanther", "", "sk_blkpanther", "jpg");
AddArt("siamese val", "", "siamese_val", "jpg");
AddArt("raqnz pre f", "", "raqnz_pre_f", "jpg");
AddArt("shea valentine", "", "shea_valentine", "jpg");
AddArt("noexceptions", "", "noexceptions", "jpg");
AddArt("play w mouse", "", "play_w_mouse", "jpg");
AddArt("mouse cool c", "", "mouse_cool_c", "jpg");
AddArt("good clean fun", "", "good_clean_fun", "jpg");
AddArt("mack", "", "mack", "jpg");
AddArt("gatonegro 1", "", "gatonegro_1", "jpg");
AddArt("fel catnmouse2", "", "fel_catnmouse2", "jpg");
AddArt("foxiehound", "", "foxiehound", "jpg");
AddArt("eclipse", "", "eclipse", "jpg");
AddArt("fel-nap2", "", "fel-nap2", "jpg");
AddArt("deerbutt", "", "deerbutt", "jpg");
AddArt("dai2", "", "dai2", "jpg");
AddArt("capturedmouse", "", "capturedmouse", "jpg");
AddArt("collaboration dragon  ff", "", "collaboration_dragon__ff", "jpg");
AddArt("2tails  fel", "", "2tails__fel", "jpg");
AddArt("aiw cheshirecat", "", "aiw_cheshirecat", "jpg");
AddArt("asb boytoy", "", "asb_boytoy", "jpg");
AddArt("ac commissions  fel", "", "ac_commissions__fel", "gif");
AddArt("squirrels", "", "squirrels", "png");
AddArt("ppg 6", "", "ppg_6", "png");
AddArt("ppg 5", "", "ppg_5", "png");
AddArt("ppg 3", "", "ppg_3", "png");
AddArt("ppg 2", "", "ppg_2", "png");
AddArt("ppg 4", "", "ppg_4", "png");
AddArt("ppg 1", "", "ppg_1", "png");
AddArt("nm thundercats ho", "", "nm_thundercats_ho", "png");
